language: python
python:
  - "2.7"

branches:
  only:
    - master
    - develop
    - feature-api
    - feature-review

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DB=sqlite
# command to run tests
script: nosetests --with-coverage

after_success:
  - coveralls
